### ISSUE TITLE
/dhcp lease, /interface show tidak bisa

### ISSUE THREAD

**Issue by jayamirudin** [dwichan0905/telegram_bot#5]
mau tanya gan untuk perintah ini tidak bisa digunakan :
/dhcp lease
/interface show

![Screenshot 2020-11-02 154839](https://user-images.githubusercontent.com/50808338/97847915-e8fe3700-1d22-11eb-94d5-c7c715cc1082.jpg)

tapi kalau perintah /interface show all dan perintah lain nya bisa
![image](https://user-images.githubusercontent.com/50808338/97847994-08955f80-1d23-11eb-8790-9cc2bc332aca.png)

apa harus ada yg di ubah di script tg_cmd_dhcp dan tg_cmd_interface ? 
kalau memang ada yg harus diubah boleh info mana saja yg di ubah?

terima kasih

**Comment by dwichan0905** [comment]
Untuk perintah ```/interface show```, tentukan dulu ethernet mana saja yang akan dikirimkan di script ```tg_cmd_interface```. 

Ubah ```eth01-router```, ```eth03-lantai-1```, ```eth04-lantai-2```, dan ```eth05-configurator``` menjadi nama ethernet yang ingin ditampilkan.
