### ISSUE TITLE
bot telegram error saat dimasukkan kedalam group Telegram

### ISSUE THREAD

**Issue by teguhpsetyo98** [dwichan0905/telegram_bot#7]
saya mengalami kendala error pada script mikrotik jika bot telegram **dimasukkan kedalam group Telegram**.

**Comment by furaihan** [comment]
mungkin bisa dijelaskan error-nya seperti apa?

**Comment by dwichan0905** [comment]
saya cek pada studi kasus yang dialami @teguhpsetyo98 (ia DM saya melalui Instagram beberapa hari lalu). Setelah bot telegram nya dimasukkan ke grup telegram, bot nya gak mau respon perintahnya, alhasil harus buat bot nya lagi tanpa dimasukkan ke grup. Beda ceritanya kalau perintah yang dikirimkan berupa pesan pribadi ke bot nya (masih work).

Mungkin untuk solusi sementaranya, hubungi bot secara pribadi... kalau udah gak respon, buat bot lagi.
